### ISSUE TITLE
'FormPlugin' object has no attribute 'email_notifications'

### ISSUE THREAD

**Issue by jvamvas** [aldryn/aldryn-forms#100] opened 2016-08-04 10:23 UTC
I have created a minimal `EmailNotificationForm` with a text field and a submit button. In the form admin's advanced settings, I've added one email notification.

Submitting the form causes the following error:

```
Request Method: POST
Request URL:    http://0.0.0.0:8000/de/kontakt/?edit
Django Version: 1.9.8
Exception Type: AttributeError
Exception Value:    
'FormPlugin' object has no attribute 'email_notifications'
Exception Location: /virtualenv/lib/python2.7/site-packages/aldryn_forms/contrib/email_notifications/cms_plugins.py in send_notifications, line 168
Python Version: 2.7.11
```

It seems that in line 168, `instance` is not of type `EmailNotificationFormPlugin` (the proxy model), but of type `FormPlugin` (the base model).

**Comment by czpython** [comment] 2016-08-04 11:16
@jvamvas 
Hello, looks like you might be using an older version of aldryn-forms.
Can you provide us with the django-cms and aldryn-forms version?

**Comment by jvamvas** [comment] 2016-08-04 12:04
@czpython 
Aldryn Forms 2.1.2
Aldryn django CMS 3.3.1.3

**Comment by czpython** [comment] 2016-08-21 14:18
Hello @jvamvas,
Sorry for the delay on this.
I've tried reproducing this issue but so far no luck.
I'm using django 1.9.8 and djangoCMS  3.3.1

The error is very strange because the cms stores a reference to the plugin class used, which means that anytime you save an advanced form it should save the reference to the `EmailNotificationForm` class and use that to load the class and send notifications.

I think the issue might be that you have both [djangocms-forms](https://github.com/mishbahr/djangocms-forms) and aldryn-forms installed.

If this is the case, we're currently looking into a solution but at the moment they're not compatible with each other due to a djangoCMS bug.

**Comment by jvamvas** [comment] 2016-08-23 18:18
No, I do not have both djangocms-forms and aldryn-forms installed.

But I was able to install the fork from #101 in my Aldryn project, so this is not a pressing issue for me.

**Comment by czpython** [comment] 2016-08-24 12:53
If this is the case then it's a deeper issue, do you mind providing us with a test project where we can reproduce this? I've tried using  both djangoCMS 3.3.1 and 3.3.2 with the latest Aldryn Forms but no luck.

**Comment by atiberghien** [comment] 2016-10-27 14:58
Still same issue here  with : 
Aldryn Forms 2.1.3.1
Aldryn django CMS 3.4.1.3 
and djangocms-forms not installed

**Comment by czpython** [comment] 2016-10-27 15:19
@atiberghien 
is this a blank project? or a project you've upgraded from older versions?
Also which django version are you using?

**Comment by atiberghien** [comment] 2016-10-27 15:29
@czpython : Blank project over Aldryn Django 1.8.15

**Comment by czpython** [comment] 2016-10-27 15:32
@atiberghien ah its an aldryn project? would you mind giving me the link to it? (email is fine) that would help me quite a lot to be able to debug this.

**Comment by atiberghien** [comment] 2016-10-27 15:41
Yep it's an Aldryn Project. You mean the «shareable link» ?

**Comment by czpython** [comment] 2016-10-27 15:43
Yes :)

**Comment by atiberghien** [comment] 2016-10-27 15:44
https://tierstruck-stage.eu.aldryn.io ?

**Comment by stefanfoulis** [comment] 2017-03-20 12:06
I'm closing this for now. Please re-open if this is still an issue.

**Closed by stefanfoulis** 2017-03-20 12:06 UTC
