### ISSUE TITLE
validate email address in advanced form recipient input field

### ISSUE THREAD

**Issue by PeterW-LWL** [aldryn/aldryn-forms#131] opened 2017-09-05 11:18 UTC
It would be good to validate the email address input field in the advanced from admin dialog, see screenshot: ![form advanced email fields](https://user-images.githubusercontent.com/14937653/30058559-d54f778e-923b-11e7-8280-8820c538cdec.png)

To be able to put anything in the input field is often a curse of problems where the page editor is not reciving any notification on form submit (even when the form user got a successful-send-email).

**Comment by czpython** [comment] 2017-09-05 12:09
Hello @PeterW-LWL,
I'm closing this as a won't fix.

The field is by design a charfield because it allows admins to define form field names as placeholder values for those fields, then when the form is submitted, those fields are filled with the respective values from the form. An EmailField would fail validation and thus not allow this feature.

**Closed by czpython** 2017-09-05 12:09 UTC

**Comment by PeterW-LWL** [comment] 2017-09-05 12:12
Okey, that makes sense. We often have the problem, that the editor puts something invalid into the from_email field like `LWL <info@lwl.org>` which results in the email not getting send at all.
