### ISSUE TITLE
Organize the form plugins hierarchically

### ISSUE THREAD

**Issue by jedie** [aldryn/aldryn-forms#150] opened 2018-02-07 10:12 UTC
Currently you can add form and fields in any order...

The "add plugin list" always contains all form plugins.

What's about to add a child/parent to create a hierarchical organization?!?

So you didn't see all form plugins in the "add plugin list", because you have to start adding **FormPlugin** first and then you can add the fields (and submit button) as childs.

**Comment by czpython** [comment] 2018-02-07 12:05
Closing as duplicate of https://github.com/aldryn/aldryn-forms/issues/1

**Closed by czpython** 2018-02-07 12:05 UTC
